-- Blizzard Mail: the "Mounts & Pets" menu.
--
-- Each entry is { itemID, "label" }. The label is only what the menu shows; hover an attachment
-- slot to see the item the server actually has under that id. Add, remove or reorder freely.
-- Keep each category under 32 entries (the 3.3.5 dropdown menu's limit).

BlizzardMailPresets = {
    {
        name = "Promo, TCG & store mounts",
        items = {
            { 49284, "Swift Spectral Tiger" },
            { 49283, "Spectral Tiger" },
            { 49285, "X-51 Nether-Rocket" },
            { 49286, "X-51 Nether-Rocket X-TREME" },
            { 49282, "Big Battle Bear" },
            { 49290, "Magic Rooster" },
            { 54811, "Celestial Steed" },
            { 43599, "Big Blizzard Bear" },
            { 37012, "The Horseman's Reins" },
            { 50250, "Big Love Rocket" },
        },
    },
    {
        name = "Rare drop mounts",
        items = {
            { 13335, "Deathcharger's Reins (Baron Rivendare)" },
            { 19902, "Swift Zulian Tiger" },
            { 19872, "Swift Razzashi Raptor" },
            { 21176, "Black Qiraji Resonating Crystal" },
            { 30480, "Fiery Warhorse's Reins (Attumen)" },
            { 32768, "Reins of the Raven Lord" },
            { 32458, "Ashes of Al'ar" },
            { 35513, "Swift White Hawkstrider" },
            { 33809, "Amani War Bear" },
            { 44151, "Blue Proto-Drake" },
            { 44168, "Time-Lost Proto-Drake" },
            { 43953, "Blue Drake (Oculus)" },
            { 43986, "Black Drake (OS 3D)" },
            { 43954, "Twilight Drake (OS 3D 25)" },
            { 43962, "White Polar Bear" },
            { 45693, "Mimiron's Head" },
            { 49636, "Onyxian Drake" },
            { 50818, "Invincible's Reins" },
        },
    },
    {
        name = "Promo, TCG & store pets",
        items = {
            { 49693, "Lil' K.T." },
            { 49665, "Pandaren Monk" },
            { 54847, "Lil' XT" },
            { 49662, "Gryphon Hatchling" },
            { 49663, "Wind Rider Cub" },
            { 56806, "Mini Thor" },
            { 49646, "Core Hound Pup" },
            { 13584, "Mini Diablo" },
            { 13583, "Panda Cub" },
            { 13582, "Zergling" },
            { 25535, "Netherwhelp" },
            { 39286, "Frosty" },
            { 20371, "Murky" },
            { 22114, "Gurky" },
            { 30360, "Lurky" },
            { 45180, "Murkimus the Gladiator" },
            { 46767, "Warbot" },
            { 34493, "Dragon Kite" },
            { 23713, "Hippogryph Hatchling" },
            { 32588, "Banana Charm" },
            { 38050, "Soul-Trader Beacon" },
            { 34492, "Rocket Chicken" },
            { 49343, "Spectral Tiger Cub" },
        },
    },
    {
        name = "Rare pets",
        items = {
            { 8494,  "Hyacinth Macaw" },
            { 8498,  "Tiny Emerald Whelpling" },
            { 8499,  "Tiny Crimson Whelpling" },
            { 10822, "Dark Whelpling" },
            { 34535, "Azure Whelpling" },
            { 11474, "Sprite Darter Hatchling" },
            { 20769, "Disgusting Oozeling" },
            { 19450, "Jubling" },
            { 33993, "Mojo" },
            { 35504, "Phoenix Hatchling" },
            { 38628, "Nether Ray Fry" },
            { 44721, "Proto-Drake Whelp" },
            { 44738, "Kirin Tor Familiar" },
            { 54436, "Blue Clockwork Rocket Bot" },
        },
    },
}
